# cargo

# [[file:~/Workspace/Programming/gchemol-rs/gchemol-readwrite/gchemol-readwrite.note::*cargo][cargo:1]]
[package]
name = "gchemol-readwrite"
version = "0.0.36"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "Reading/writing chemical objects for gchemol"
homepage = "https://github.com/gchemol/gchemol-readwrite"
repository = "https://github.com/gchemol/gchemol-readwrite"
license = "MIT OR Apache-2.0"

[dependencies]
tempfile = "3"
nom = "5"
serde = {version="1", features = ["derive"]}
serde_json = "1.0"
regex = "1"
indexmap = "1.0"
handlebars = "3"
tera = "1"
gchemol-gut = "0.0.7"
gchemol-core = "0.0.37"
gchemol-parser = { version = "0.0.7", features = ["adhoc"] }

[dev-dependencies]

[features]
adhoc = []
# cargo:1 ends here
