# cargo

# [[file:~/Workspace/Programming/gchemol-rs/gchemol-readwrite/gchemol-readwrite.note::*cargo][cargo:1]]
[package]
name = "gchemol-readwrite"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
nom = "5"
guts = { git = "https://github.com/ybyygu/guts.git" }
gchemol-core = { path = "../gchemol-core" }
text-parser = { path = "../parser", features = ["adhoc"] }

[dev-dependencies]
# cargo:1 ends here
