# cargo

# [[file:~/Workspace/Programming/gchemol-rs/gchemol-readwrite/gchemol-readwrite.note::*cargo][cargo:1]]
[package]
name = "gchemol-readwrite"
version = "0.1.0-alpha1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
tempfile = "3"
nom = "5"
serde = {version="1", features = ["derive"]}
serde_json = "1.0"
regex = "1"
indexmap = "1.0"
handlebars = "3"
tera = "1"
#guts = { git = "https://github.com/ybyygu/guts.git", branch="dev" }
guts = { path = "../../guts" }
gchemol-core = { path = "../gchemol-core" }
text-parser = { path = "../parser", features = ["adhoc"] }

[dev-dependencies]

[features]
adhoc = []
# cargo:1 ends here
